# Generated by Django 4.1.3 on 2022-11-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('케이크', '케이크'), ('스콘', '스콘'), ('휘낭시에', '휘낭시에'), ('쿠키', '쿠키')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'post',
                'ordering': ['-createdAt'],
            },
        ),
    ]
