# Generated by Django 4.1.3 on 2022-11-15 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default=None, null=True, upload_to='postpictures/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postpicture', to='post.post')),
            ],
        ),
    ]
