# Generated by Django 4.1.3 on 2022-11-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postpicture'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postpicture',
            table='post_picture',
        ),
    ]
